// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrz5cZC-9ZbgMnxGNY6qJ8q4nMI2_dlk',
    appId: '1:899930397516:web:316076cd3be987f89ccde9',
    messagingSenderId: '899930397516',
    projectId: 'kneipentour-a270f',
    authDomain: 'kneipentour-a270f.firebaseapp.com',
    storageBucket: 'kneipentour-a270f.firebasestorage.app',
    measurementId: 'G-HD2B50CJ75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02ZKDfmU4AXokG7hEKIFrIFWnJp0m5PQ',
    appId: '1:899930397516:android:d57de99ae01c856b9ccde9',
    messagingSenderId: '899930397516',
    projectId: 'kneipentour-a270f',
    storageBucket: 'kneipentour-a270f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlaSk4EDgENEblA-HSROKSpG-TXYryEQ0',
    appId: '1:899930397516:ios:0424b11c1eed2c4e9ccde9',
    messagingSenderId: '899930397516',
    projectId: 'kneipentour-a270f',
    storageBucket: 'kneipentour-a270f.firebasestorage.app',
    iosBundleId: 'com.example.kneipentour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlaSk4EDgENEblA-HSROKSpG-TXYryEQ0',
    appId: '1:899930397516:ios:0424b11c1eed2c4e9ccde9',
    messagingSenderId: '899930397516',
    projectId: 'kneipentour-a270f',
    storageBucket: 'kneipentour-a270f.firebasestorage.app',
    iosBundleId: 'com.example.kneipentour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIrz5cZC-9ZbgMnxGNY6qJ8q4nMI2_dlk',
    appId: '1:899930397516:web:42ffe4e1ae6aafc29ccde9',
    messagingSenderId: '899930397516',
    projectId: 'kneipentour-a270f',
    authDomain: 'kneipentour-a270f.firebaseapp.com',
    storageBucket: 'kneipentour-a270f.firebasestorage.app',
    measurementId: 'G-JLNLKWPH4G',
  );
}
